# -*- coding: utf-8 -*-
"""zenginlikexe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqomRA5IBc4y6o7xV_aCCDhwbsGgJi2L
"""

!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar xvzf ta-lib-0.4.0-src.tar.gz
import os

os.chdir('ta-lib') # Can't use !cd in co-lab
!./configure --prefix=/usr
!make
!make install
# wait ~ 30s
os.chdir('../')
!ls
!pip install TA-Lib
import talib
!pip install pandas-ta
!pip install python-binance





# -*- coding: utf-8 -*-
"""
Created on Mon May 10 01:14:23 2021

@author: yazılım
"""


import talib as ta
import pandas_ta as pd_ta
import pandas as pd

import time
from binance.enums import *
from binance.client import Client
from binance.client import Client
import numpy as np
#import xlwings as xw
from datetime import datetime

api_key=""
api_secret=""


client = Client(api_key, api_secret)




kac_usdt_ile_baslanacak =200

#wb = xw.Book('coinListe.xlsx')
#sht = wb.sheets['Sayfa1']

kac_usdt_ile_baslanacak=int(kac_usdt_ile_baslanacak)+1

#GECİCİ
#kac_usdt_ile_baslanacak=30

semboller=[]


# -*- coding: utf-8 -*-
"""
Created on Mon May 10 01:14:23 2021

@author: yazılım
"""
global adana_parasi
adana_parasi=1000


tickers = client.get_ticker()


uzunluk_listenin=int(len(tickers))

semboller=[]
degerler=[]
for qe in range(0,uzunluk_listenin):
        
    if (tickers[qe]["symbol"][-4:]) =="USDT" :
        
        
        siralama_icin_bakiyorum=(tickers[qe]["priceChangePercent"])
        
        degerler.append(float(siralama_icin_bakiyorum))
  
    
  
    
degerler.sort(reverse=True)
        

uzunluk_degerlerin=int(len(degerler))      



for yummi in range(0,uzunluk_listenin):

    for qeq in range(0,uzunluk_listenin):   
        if ((tickers[qeq]["symbol"][-4:]) =="USDT" ):
        
            try:              
       
                if degerler[yummi]==float(tickers[qeq]["priceChangePercent"]):
                    print("para",(tickers[qeq]["symbol"])) 
                    print("değer",degerler[yummi])
                    semboller.append((tickers[qeq]["symbol"])+",1,rsi,"+str(degerler[yummi]))
            except:
                pass              
        
        
semboller=semboller[:200]

#semboller.reverse()
#semboller
kac_usdt_ile_baslanacak=int(len(semboller))
print("sembolleri yazdırıyorum")
for i in semboller:
    print(i)
print("kaç tane coin var:",len(semboller))
            
        
"""
yasakli_kelimeler=["DOWN","BULL","UP","BEAR"]


for yasakli_bul in semboller:
    yasakli_kelime_bulma=str(yasakli_bul)
    for ikinci_bulma_listesi in range(0,4):
        if yasakli_kelime_bulma.find(yasakli_kelimeler[ikinci_bulma_listesi])!=-1:
            print(yasakli_kelime_bulma)
            semboller.remove(yasakli_kelime_bulma)
    
    

"""

       


#symbol = 'WINUSDT'
interval = '1m'
interval_15="15m"
limit = 500


#log kaydı için



artis_pozitif_mi="ADANA"
islem_sayisi=0

an = datetime.now()
saat1=an.hour
saat2=saat1+1

if saat2>23:
    saat2=24-saat2
    saat2=abs(saat2)

Batu_buldu_sonra="ADANA"
Batu_buldu_once="ADANA"


with open("log.txt", "a") as dosya:
    ana = datetime.now()
    timeS=ana
    dosya.write(str(timeS))    
    dosya.write("başladım")
    dosya.write("\n")
dosya.close()

while True:
    try:
        print("döngüye başladım")

           
    

        try:
                
            for i in range(0,(kac_usdt_ile_baslanacak-1)):
                    
                    Sembol_Suan=semboller[i]
                    Sembol_Suan=Sembol_Suan.split(",")
                    print("şu anki sembol:",Sembol_Suan[0])
                    time.sleep(7)
                    #hesap bakiyesi
                    try:
                    
                        
                        tickers = client.get_ticker()
                        info = client.get_account()
                        #yüzde artış bulma
                        len_tickers=int(len(tickers))
                        for er in range(0,len_tickers):   
                            yuzde_artis_bulma=tickers[er]
                                   
                            for sembol,deger in yuzde_artis_bulma.items():
                                #print(deger)
                                if deger==Sembol_Suan[0]:

                                    sirasi=er
                        verileri_al=tickers[sirasi]  
                        
                        yuzde=verileri_al["priceChangePercent"]
                        
                        yuzde_duzenli=yuzde
                        yuzde_duzenli=yuzde.split("-" or "+")
                        yuzde_arti_mi_eksi_mi=yuzde[0]
                        
                        ##### normalde burası bir ama + - de bir bug var şuanlık 0 ypıyorum
                            
                        if yuzde_arti_mi_eksi_mi == "-":
                                yuzde_arti_mi_eksi_mi="-"
                                artis_pozitif_mi=False
                                
                        else:
                                yuzde_arti_mi_eksi_mi="+"
                                artis_pozitif_mi=True                        
                        
                        infok=info["balances"]
                        for k in range(0,417):   
                            b=infok[k]
                            for para,miktar in b.items():
                                uwu=Sembol_Suan[0]
                                uwu=uwu[:-4]
                                if miktar ==(uwu):
                                    Nerede_bu_da=k
                             
                        verileri_al_almakicin=infok[Nerede_bu_da]           
                        bende_ne_kadar_var=verileri_al_almakicin["free"]
                    
                    except:
                        print("hata")
            
            
                #HESAP VERİSİ ÇEKME BİTTİ
                
                
                
                
                
                
                # 10 saniye bekliyoruz. Sürekli sorgu göndermeye gerek yok.
                    try:
                        
                        #veri çektim
                        klines = client.get_klines(symbol=Sembol_Suan[0], interval=interval, limit=limit)
                        
                        #ayrıştırma  1 saat için
                        
                        open = [float(entry[1]) for entry in klines]
                        high = [float(entry[2]) for entry in klines]
                        low = [float(entry[3]) for entry in klines]
                        
                        close = [float(entry[4]) for entry in klines]
                        last_closing_price = close[-1]
                        previous_closing_price = close[-2]
                        close_array = np.asarray(close)
                        close_finished = close_array[:-1]
                        
                        #RSI hesaplama
                        rsi = ta.RSI(close_finished, timeperiod=52)
                        #1 MUM öncesi
                        rsi_last = rsi[-1]
                        #2 MUM öncesi
                        rsi_last_2mum = rsi[-2]
                        #ema hesaplama
                        
                        df = pd.DataFrame(close,columns =['degerler'])   
                        
                        ema_5=pd_ta.ema(df["degerler"], length=5)                                           
                        ema_5=ema_5[499]    
                        
                        ema_6=pd_ta.ema(df["degerler"], length=6)                                           
                        ema_6=ema_6[499] 
                        
                        ema_9=pd_ta.ema(df["degerler"], length=9)       
                        ema_9=ema_9[499]
                        
                        #şuan
                        ema_7=pd_ta.ema(df["degerler"], length=7)       
                        ema_7=ema_7[499]
                        #2 önce
                        ema_7_pre_1=pd_ta.ema(df["degerler"], length=7)       
                        ema_7_pre_1=ema_7_pre_1[498]
                        #3 önce
                        ema_7_pre_2=pd_ta.ema(df["degerler"], length=7)       
                        ema_7_pre_2=ema_7_pre_2[497]
                        #4 önce
                        ema_7_pre_3=pd_ta.ema(df["degerler"], length=7)       
                        ema_7_pre_3=ema_7_pre_3[496]
                        #5 önce
                        ema_7_pre_4=pd_ta.ema(df["degerler"], length=7)       
                        ema_7_pre_4=ema_7_pre_4[495]
                        
                        

                        #şuan ema_3
                        ema_3=pd_ta.ema(df["degerler"], length=3)       
                        ema_3=ema_3[499]
                        #2 önce ema_3
                        ema_3_pre1=pd_ta.ema(df["degerler"], length=3)       
                        ema_3_pre1=ema_3_pre1[498]
                        #3 önce ema_3
                        ema_3_pre2=pd_ta.ema(df["degerler"], length=3)       
                        ema_3_pre2=ema_3_pre2[497]
                        #4 önce ema_3
                        ema_3_pre3=pd_ta.ema(df["degerler"], length=3)       
                        ema_3_pre3=ema_3_pre3[496]
                        #5 önce ema_3
                        ema_3_pre4=pd_ta.ema(df["degerler"], length=3)       
                        ema_3_pre4=ema_3_pre4[495]
                        #6 önce ema_3
                        ema_3_pre5=pd_ta.ema(df["degerler"], length=3)       
                        ema_3_pre5=ema_3_pre5[494]
                        
                        #ema_15=pd_ta.ema(df["degerler"], length=15)       
                        #ema_15=ema_15[499]
                        
                        ema_29=pd_ta.ema(df["degerler"], length=29)       
                        ema_29=ema_29[499]
                        
                        # 15 dk lık emalar
                        
                        time.sleep(7)
                        klines_15 = client.get_klines(symbol=Sembol_Suan[0], interval=interval_15, limit=limit)
                        
                        #ayrıştırma  1 saat için
                        
                        open = [float(entry[1]) for entry in klines_15]
                        high = [float(entry[2]) for entry in klines_15]
                        low = [float(entry[3]) for entry in klines_15]
                        
                        close_15 = [float(entry[4]) for entry in klines_15]
                        last_closing_price = close_15[-1]
                        previous_closing_price = close_15[-2]
                        close_array = np.asarray(close_15)

                        df = pd.DataFrame(close_15,columns =['degerler'])   
                        
                        klines15_ema_5=pd_ta.ema(df["degerler"], length=5)                                           
                        klines15_ema_5=klines15_ema_5[499]    
                        
                        klines15_ema_6=pd_ta.ema(df["degerler"], length=6)                                           
                        klines15_ema_6=klines15_ema_6[499] 
                        
                        klines15_ema_9=pd_ta.ema(df["degerler"], length=9)       
                        klines15_ema_9=klines15_ema_9[499]
                        
                        #şuan
                        klines15_ema_7=pd_ta.ema(df["degerler"], length=7)       
                        klines15_ema_7=klines15_ema_7[499]
                        #2 önce
                        klines15_ema_7_pre_1=pd_ta.ema(df["degerler"], length=7)       
                        klines15_ema_7_pre_1=klines15_ema_7_pre_1[498]
                        #3 önce
                        klines15_ema_7_pre_2=pd_ta.ema(df["degerler"], length=7)       
                        klines15_ema_7_pre_2=klines15_ema_7_pre_2[497]
                        #4 önce
                        klines15_ema_7_pre_3=pd_ta.ema(df["degerler"], length=7)       
                        klines15_ema_7_pre_3=klines15_ema_7_pre_3[496]
                        #5 önce
                        klines15_ema_7_pre_4=pd_ta.ema(df["degerler"], length=7)       
                        klines15_ema_7_pre_4=klines15_ema_7_pre_4[495]
                        
                        

                        #şuan klines15_ema_3
                        klines15_ema_3=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3=klines15_ema_3[499]
                        #2 önce klines15_ema_3
                        klines15_ema_3_pre1=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3_pre1=klines15_ema_3_pre1[498]
                        #3 önce klines15_ema_3
                        klines15_ema_3_pre2=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3_pre2=klines15_ema_3_pre2[497]
                        #4 önce klines15_ema_3
                        klines15_ema_3_pre3=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3_pre3=klines15_ema_3_pre3[496]
                        #5 önce klines15_ema_3
                        klines15_ema_3_pre4=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3_pre4=klines15_ema_3_pre4[495]
                        #6 önce klines15_ema_3
                        klines15_ema_3_pre5=pd_ta.ema(df["degerler"], length=3)       
                        klines15_ema_3_pre5=klines15_ema_3_pre5[494]

                        
                        klines15_ema_29=pd_ta.ema(df["degerler"], length=29)       
                        klines15_ema_29=klines15_ema_29[499]

                        
                        
                        """
                        
                        bakalım olacak mı burası biraz karışık gibi ama olur bence
                        
                        """
                        IKI_MUM_SONRASI_POZ_EMA3=ema_3+ema_3_pre1
                        IKI_MUM_SONRASI_POZ_EMA7=ema_7+ema_7_pre_1
                        
                        Arti_taraf_buranin_poz_olmasi_lazim=IKI_MUM_SONRASI_POZ_EMA3-IKI_MUM_SONRASI_POZ_EMA7
                        
                        if Arti_taraf_buranin_poz_olmasi_lazim >= 0:
                           Batu_buldu_sonra=True
                        else:
                           Batu_buldu_sonra=False
                        
                        UC_MUM_ONCESI_NEG_EMA3=ema_3_pre2+ema_3_pre3+ema_3_pre4
                        UC_MUM_ONCESI_NEG_EMA7=ema_7_pre_2+ema_7_pre_3+ema_7_pre_4

                        Eksi_taraf_poz_cikmasi_lazim=UC_MUM_ONCESI_NEG_EMA7-UC_MUM_ONCESI_NEG_EMA3
                        
                        if Eksi_taraf_poz_cikmasi_lazim >= 0:
                           Batu_buldu_once=True
                        else:
                           Batu_buldu_once=False
                        
                        print("-------------Ema kontrolü 1 saat --------------")
                        
                        print("işlem sayısı",islem_sayisi)
                        print("ema 3 oranı:",ema_3)
                        print("ema 7 oranı:",ema_7)
                        print("ema 29 oranı:",ema_29)
                        print("-------------Ema kontrolü 15 --------------")
                        print("ema 3 oranı:",klines15_ema_3)
                        print("ema 7 oranı:",klines15_ema_7)
                        print("ema 29 oranı:",klines15_ema_29)
                        print("------------- Diğer datalar --------------")
                        print("Önceki mumlar sağlıyor mu:",Batu_buldu_once)
                        print("Sonraki mumlar sağlıyor mu:",Batu_buldu_sonra)
                        print("artış pozitiftir: ",artis_pozitif_mi)
                        print("artış oranı:",yuzde)
                        try:
                            print("satış yapmalı mı:",Sembol_Suan_d[3])
                        except:
                            pass
                        
                       
                        
                        
                        
                        try:
                            ana = datetime.now()
                            timeS=ana    
                            print("saat:",timeS)
                        except:
                            pass
                        
                        #log kaydı
                        
                        
                        
                        
                        """
                        
                        try:
                                            info = client.get_account()
                                            infok=info["balances"]
                                            for hebele in range(0,413):   
                                                            b=infok[hebele]
                                                            for para,miktar in b.items():
                                                                uwu=Sembol_Suan[0]
                                                                uwu=uwu[:-4]
                                                                if miktar ==(uwu):
                                                                    Nerede_bu_da=hebele
                                                             
                                            verileri_al_almakicin=infok[Nerede_bu_da]           
                                            bende_ne_kadar_var=verileri_al_almakicin["free"]
                                            
                                            #ebemi s2kim
                                            deneme=float(bende_ne_kadar_var)
                                            try:
                                                
                                                if float(deneme)*float(last_closing_price) < 3:
                                                    kaydedici=(Sembol_Suan[0])+",1,"
                                            
                                                    print("kaydedici:",kaydedici)
    
                                                
                                                    semboller[i]=kaydedici 
                                            except Exception as e:
                                                print("salak mustafa sikik hem de iç hatası :", str(e))   
                                                
                        except Exception as e:
                            print("salak mustafa sikik hem de dış hatası :", str(e))
                                                              
                        """
                        


                        #bu kısım bizim %1 lik azalmada satış yapar mı yapmaz mı kontrol ediyor
                        """
                        
                        akıllı batu
                        
                        """
                        #################################################
                        """
                        tickers = client.get_ticker()
                        info = client.get_account()
                        #yüzde artış bulma
                        
                        for wan in range(0,(kac_usdt_ile_baslanacak-1)): 
                                #print("mal mıyım 1")
                                for sembol,deger in yuzde_artis_bulma.items():
                                    try:
                                        if deger==Sembol_Suan_d[0] and Sembol_Suan_d[3] ==1 and Sembol_Suan_d[1] == 0 :
                                             for erekE in range(0,1445):   
                                                yuzde_artis_bulma=tickers[erekE]
                                                print("satış durumuna gelindi:",Sembol_Suan_d[0])
                                                 
                                                sirasi=erekE
                                                verileri_al=tickers[sirasi]
                                                salak_mustafa_orani=verileri_al["lastPrice"]

                                                if float(Sembol_Suan_d[2]) > float(salak_mustafa_orani):
                                                  

                                                
                                                  print("satış")
                                                          
                                                  
                                                  print("satım yapmaya çalışıyorum")
                                                  
                                                  info = client.get_account()
                                                  infok=info["balances"]
                                                  for hebele in range(0,413):   
                                                                          b=infok[hebele]
                                                                          for para,miktar in b.items():
                                                                              uwu=Sembol_Suan_d[0]
                                                                              uwu=uwu[:-4]
                                                                              if miktar ==(uwu):
                                                                                  Nerede_bu_da=hebele
                                                                          
                                                  verileri_al_almakicin=infok[Nerede_bu_da]           
                                                  bende_ne_kadar_var=verileri_al_almakicin["free"]
                                                          
                                                          #ebemi s2kim
                                                  deneme=float(bende_ne_kadar_var)
                                                          
                                                  deneme=float(bende_ne_kadar_var)
                                                  
                                                  try:
                                                      orders = client.get_open_orders(symbol=Sembol_Suan_d[0])
                                                      
                                                      iptal_emir_icin_order_id=orders[0]["orderId"]
                                                      
                                                      result = client.cancel_order(
                                                          symbol=Sembol_Suan_d[0],
                                                          orderId=str(iptal_emir_icin_order_id))
                                                      
                                                  except Exception as e:
                                                      print ("verilmiş bir emir yok hatası : " , str(e))
                                                          
                                                  for w in range(-6,-3):
                                                              
                                                              
                                                              time.sleep(7) 
                                                              try:
                                                                      
                                                                  deneme=str(deneme)[:-w]
                                                                  deneme=float(deneme)
                                                                  print(deneme)
                                                                  
                                                                  order = client.order_market_sell(
                                                                      symbol=Sembol_Suan_d[0],
                                                                      quantity=deneme
                                                                      )
                                                                  
                                                                  print("satış yapıldı")
                                                                  semboller[i]=(Sembol_Suan_d[0])+",1"
                                                                  islem_sayisi=islem_sayisi+1
                                                                  print("şu kadar usdt ye sattık:",order["cummulativeQuoteQty"])
                                                                  print(semboller[i])
                                                              except Exception as e:
                                                                  print("hata sikik mustafa kısmı iç:", str(e))
                                                  try:
                                                      with open("log_yeni_dusus_tetiklenme.txt", "a") as dosya:
                                                          ana = datetime.now()
                                                          timeS=ana
                                                          dosya.write(str(timeS))    
                                                          dosya.write("şu kadar usdt ye sattık:",order["cummulativeQuoteQty"])
                                                          dosya.write("\n")
                                                      dosya.close()
                                                  except Exception as e:
                                                    print ("hata kaydetme: " , str(e))
                                                    pass
              
                                                 
                                                 
                                    except:
                                        pass
                        """
                        #################################################
                        """
                        for erekE in range(0,1445):   
                            yuzde_artis_bulma=tickers[erekE]
                             
                            for wan in range(0,(kac_usdt_ile_baslanacak-1)): 
                            
                                for sembol,deger in yuzde_artis_bulma.items():
                                    try:
                                        
                                        print(deger)
                        
                                        Sembol_Suan_d=semboller[wan]
                                        Sembol_Suan_d=Sembol_Suan_d.split(",")
                                        #print("şu anki sembol:",Sembol_Suan_d[0])
                                        try:
                                            
                                            if deger==Sembol_Suan_d[0] and Sembol_Suan_d[3] ==1 and Sembol_Suan_d[1] == 0 :
                                                
            
                                                sirasi=erekE
                                                verileri_al=tickers[sirasi]
                                                salak_mustafa_orani=verileri_al["lastPrice"]
                                                float(Sembol_Suan_d[2])>float(salak_mustafa_orani)
                                                
                                                print("satış")
                                                        
                                                
                                                print("satım yapmaya çalışıyorum")
                                                
                                                info = client.get_account()
                                                infok=info["balances"]
                                                for hebele in range(0,413):   
                                                                        b=infok[hebele]
                                                                        for para,miktar in b.items():
                                                                            uwu=Sembol_Suan_d[0]
                                                                            uwu=uwu[:-4]
                                                                            if miktar ==(uwu):
                                                                                Nerede_bu_da=hebele
                                                                         
                                                verileri_al_almakicin=infok[Nerede_bu_da]           
                                                bende_ne_kadar_var=verileri_al_almakicin["free"]
                                                        
                                                        #ebemi s2kim
                                                deneme=float(bende_ne_kadar_var)
                                                        
                                                deneme=float(bende_ne_kadar_var)
                                                
                                                try:
                                                    orders = client.get_open_orders(symbol=Sembol_Suan_d[0])
                                                    
                                                    iptal_emir_icin_order_id=orders[0]["orderId"]
                                                    
                                                    result = client.cancel_order(
                                                        symbol=Sembol_Suan_d[0],
                                                        orderId=str(iptal_emir_icin_order_id))
                                                    
                                                except Exception as e:
                                                    print ("verilmiş bir emir yok hatası : " , str(e))
                                                        
                                                for w in range(-6,-3):
                                                            
                                                            
                                                            time.sleep(7) 
                                                            try:
                                                                    
                                                                deneme=str(deneme)[:-w]
                                                                deneme=float(deneme)
                                                                print(deneme)
                                                                
                                                                order = client.order_market_sell(
                                                                    symbol=Sembol_Suan_d[0],
                                                                    quantity=deneme
                                                                    )
                                                                
                                                                print("satış yapıldı")
                                                                semboller[i]=(Sembol_Suan_d[0])+",1"
                                                                islem_sayisi=islem_sayisi+1
                                                                print("şu kadar usdt ye sattık:",order["cummulativeQuoteQty"])
                                                                print(semboller[i])
                                                            except Exception as e:
                                                                print("hata sikik mustafa kısmı iç:", str(e))
        
    
                                        except Exception as e:
                                            print("hata sikik mustafa kısmı dış:", str(e))
                                    except Exception as e:
                                            print("hata sikik mustafa kısmı dış2:", str(e))
                        """    
                        #if artis_pozitif_mi==True:
                                
                            #alım satım işemleri
                        if (Sembol_Suan[1]=="1"):
                            if artis_pozitif_mi==True:
                                
                                #yuzde_beslik_fark=(rsi_last-rsi_last_2mum)
                                #print("rsi %5 lik farkı:",yuzde_beslik_fark)
                                #print("alım yapmaya çalışıyorum")
                                if ema_3 > ema_7 and rsi_last <= 54 and rsi_last > rsi_last_2mum and klines15_ema_3 > klines15_ema_7 :
                                    
                                    try:
                                        print("Alırdım")
                                        
                                                
                                            

                                        TUTAR=(40/last_closing_price)
                                        
                                        print("şu kadar tane alıyorum :",TUTAR)
                                         
                                        order = client.order_market_buy(
                                                symbol=Sembol_Suan[0],
                                                quantity=float(round(TUTAR, 1)),
                                                )
                                        
                                        yuzde_kirk_artis=order["fills"][0]
                                        yuzde_kirk_artis=yuzde_kirk_artis["price"]
                                        yuzde_kirk_artis=float(last_closing_price)+float(last_closing_price)*3/100
                                        yuzde_kirk_azalis=float(last_closing_price)-float(last_closing_price)*1.5/100
                                        
                                        kaydedici=(Sembol_Suan[0])+",1,"+str(yuzde_kirk_azalis)+",1"
                                        
                                        print("kaydedici:",kaydedici)

                                            
                                        semboller[i]=kaydedici        
                                    
                                    
                                        print("alım yaptık") 
                                        
                                        try:
                                            with open("log_yeni_alım.txt", "a") as dosya:
                                                ana = datetime.now()
                                                timeS=ana
                                                dosya.write(str(timeS))    
                                                dosya.write("alım yaptık",str(kaydedici))
                                                dosya.write("\n")
                                            dosya.close()
                                        except Exception as e:
                                            print ("hata kaydetme: " , str(e))
                                            pass
                                        
                                        #satış emri koyulacak
                                        try:
                                            time.sleep(4)
                                            
                                            info = client.get_account()
                                            infok=info["balances"]
                                            for k in range(0,413):   
                                                        b=infok[k]
                                                        for para,miktar in b.items():
                                                            uwu=Sembol_Suan[0]
                                                            uwu=uwu[:-4]
                                                            if miktar ==(uwu):
                                                                Nerede_bu_da=k
                                                         
                                            verileri_al_almakicin=infok[Nerede_bu_da]           
                                            bende_ne_kadar_var=verileri_al_almakicin["free"]
                                                                                
                                            for emir_tutari in (4,2):    
                                                Emir_Koyualacak_tutar=last_closing_price+last_closing_price*1/100
                                                belirtec="%0."+str(emir_tutari)+"f"
                                                Emir_Koyualacak_tutar=(belirtec % (Emir_Koyualacak_tutar))
                                                print(Emir_Koyualacak_tutar)
                                                
                                                
                                                try:
                                                    
                                                    
                                                                                
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    deneme=float(bende_ne_kadar_var)
                                                    print("elimde olan koin:",deneme)
                                                
                                                     
                                                    for w in range(-6,-3):
                                                        
                                                        
                                                        time.sleep(4) 
                                                        try:
                                                                
                                                            deneme=str(deneme)[:-w]
                                                            deneme=float(deneme)
                                                            print(deneme)
                                                                                
                                                    
                                                            print("satmaya çalışılan miktar:",deneme)
                
                
                                                            try:
                                                                
                                                                order = client.order_limit_sell(
                                                                        symbol=(Sembol_Suan[0]),
                                                                        quantity=deneme,
                                                                        price=float(Emir_Koyualacak_tutar))
                                                                
                                                                            
                                                                print("satış emri verildi")
                                                                
                                                                
                                                                
                                                            except Exception as e:
                                                                    print("hata kodusatıs emri içeri:", str(e))
                                                        except Exception as e:
                                                                    print("hata kodusatıs emri içeri 2:", str(e))
                                                    try:
                                                        with open("log_yeni_alım.txt", "a") as dosya:
                                                            ana = datetime.now()
                                                            timeS=ana
                                                            dosya.write(str(timeS))    
                                                            dosya.write("alım yaptık ve emir koyduk",str(Emir_Koyualacak_tutar))
                                                            dosya.write("\n")
                                                        dosya.close()
                                                    except:
                                                        pass                
                                                        
                                                except Exception as e:
                                                    print ("hata kodu satıs emri dışarı: " , str(e))
                                                    
                                        except Exception as e:
                                                print ("hata kodu satıs emri dışarı emir tutarı kısmı: " , str(e))
                                            
                                          
                                        
                                        
                                        
                                    except Exception as e:
                                        print ("hata kodu market alış : " , str(e))
                                    
                                    
                                        
                        #elif artis_pozitif_mi==False:
                            #alım satım işemleri
                            #satış durumuna geçiyoruz.
                            
                            
                        elif (Sembol_Suan[1]=="sifiryapburayı"):
                                print("satmaya çalışıyorum")

                                
                                
                                #print("bir önceki en yüksek rsi değeri:",float(Sembol_Suan[2]))
                                #print("şu an en yüksek rsi değeri:",float(rsi_last))
                                
                                #if ema_5 > float(Sembol_Suan[2]):
                                    
                                    #semboller[i]=(Sembol_Suan[0])+",0,"+str(ema_5)
                                #else:
                                    # %10 luk rsi azalış hesaplaması                                   
                                try:
                                        #ema_satıs_tetik=(ema_5-ema_5*0.2/100)
                                        #ema_satıs_tetik=(float(Sembol_Suan[2])-float(Sembol_Suan[2])*0.2/100)
                                        
                                        #print("ema satış tetik:",ema_satıs_tetik)
                                                                                
                                                                                
                                                                                
                                        

                                        
                                        
                                        
                                        if klines15_ema_3 <= klines15_ema_7:
                                            
                                            #emir varsa iptal etmek için
                                            
                                            try:
                                                orders = client.get_open_orders(symbol=Sembol_Suan[0])
                                                
                                                iptal_emir_icin_order_id=orders[0]["orderId"]
                                                
                                                result = client.cancel_order(
                                                    symbol=Sembol_Suan[0],
                                                    orderId=str(iptal_emir_icin_order_id))
                                                
                                            except Exception as e:
                                                print ("verilmiş bir emir yok hatası : " , str(e))
                                                
                                            print("satış yapılacak")
                                            
                                    
                                            print("satım yapmaya çalışıyorum")
                                            
                                            
                                            try:
                                                time.sleep(4)
                                                
                                                info = client.get_account()
                                                infok=info["balances"]
                                                for k in range(0,413):   
                                                            b=infok[k]
                                                            for para,miktar in b.items():
                                                                uwu=Sembol_Suan[0]
                                                                uwu=uwu[:-4]
                                                                if miktar ==(uwu):
                                                                    Nerede_bu_da=k
                                                             
                                                verileri_al_almakicin=infok[Nerede_bu_da]           
                                                bende_ne_kadar_var=verileri_al_almakicin["free"]
                                            except:
                                                pass
                                            
                                            #deneme=float(Sembol_Suan[3])
                                            deneme=float(bende_ne_kadar_var)
                                            for w in range(-6,-3):
                                                
                                                
                                                time.sleep(7) 
                                                try:
                                                    
                                                    deneme=str(deneme)[:-w]
                                                    deneme=float(deneme)
                                                    print(deneme)
                                                    
                                                    order = client.order_market_sell(
                                                        symbol=Sembol_Suan[0],
                                                        quantity=deneme
                                                        )
                                                    
                                                    
                                                    
                                                    print("satış yapıldı")
                                                        
                                                  
                                                    semboller[i]=(Sembol_Suan[0])+",1"
                                                    islem_sayisi=islem_sayisi+1
                                                    print("şu kadar usdt ye sattık:",order["cummulativeQuoteQty"])
                                                    print(semboller[i])
                                                    try:
                                                        with open("log_yeni_satıs.txt", "a") as dosya:
                                                            ana = datetime.now()
                                                            timeS=ana
                                                            dosya.write(str(timeS))    
                                                            dosya.write("şu kadar usdt ye sattık:",order["cummulativeQuoteQty"])
                                                            dosya.write("\n")
                                                        dosya.close()
                                                    except Exception as e:
                                                        print ("hata kaydetme: " , str(e))
                                                        pass 
                                                except Exception as e:
                                                    print("hata kodusatıs 1 iç:", str(e))
                                            
                                            
                                            #satıs_log_para=float(bende_ne_kadar_var)*float(last_closing_price)
                                            #adana_parasi=float(adana_parasi)+float(satıs_log_para)
                                            #print("satış sonrası adana parası:",adana_parasi)    
                                    
                        
                                    
                                except Exception as e:
                                    print("hata kodu satıs 2 dış:", str(e))
                                        
                                        

                                    
                                    
                                        
                                
                               
                    except Exception as e:
                        print("kripto:", str(e))
                        pass
        except Exception as e:
                try:                   
                    print("hata kodu en son eklediğimde gerçekleşti:", str(e))
                    client = Client(api_key, api_secret)
                except:
                    pass
    except:
        try:
                
            print("selamke başa dön")
            client = Client(api_key, api_secret)
        except:
            pass

!pip install -U git+https://github.com/twopirllc/pandas-ta





